# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'categories',
                'verbose_name': 'category',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='movies/%Y/%m/%d')),
                ('description', models.TextField()),
                ('runtime', models.CharField(max_length=15)),
                ('year', models.CharField(max_length=4)),
                ('formatt', models.CharField(max_length=15)),
                ('category', models.ManyToManyField(blank=True, related_name='category_movie', to='catalogo.Category')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AlterIndexTogether(
            name='movie',
            index_together=set([('id', 'slug')]),
        ),
    ]
