# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 16:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='user_movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movie_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
