# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_movie_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='fecha',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
